### ISSUE TITLE
Error when using custom validation rules in Meerkat blueprint

### ISSUE THREAD

**Issue by arkraieski** [Stillat/meerkat-statamic3#239]
Hi, I'm not sure if this is a bug or unsupported functionality (or if it's possible I'm just doing something wrong), but as far as I can tell, custom Laravel validation does not work. I am on statamic 4.55.0 and meerkat 3.1.1

As a reproducible example, I followed the [statamic and laravel docs](https://statamic.dev/validation#custom-rules) in defining a custom `Uppercase` validation rule and referenced it in the meerkat blueprint yaml:
```
            handle: email
            field:
              type: text
              display: Email
              validate:
                - required
                - email
                - new App\Rules\Uppercase
```

Then, when I attempt to submit a comment, it throws an error:
`ERROR: Method Illuminate\Validation\Validator::validateNewApp\Rules\Uppercase does not exist.`

I confirmed that the same validation rule class worked with other (non-meerkat related) blueprints in my control panel.

My real use case for custom validation rules is that I am trying to prevent guest commenters from using email addresses that look like those of site administrators.
